// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace me.caneva20.ConfigAssets.Editor.Builders
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\dev\unity\ConfigAssets\Assets\config-assets\Editor\Builders\EnhancedConfigurationGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class EnhancedConfigurationGenerator : EnhancedConfigurationGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("////////////////////////////////////////////////////////////////////////////////\r\n// This file is auto-generated by ConfigAssets package.\r\n// Do not modify this file.\r\n// It will be overwritten next time the generator is run.\r\n//////////////////////////////////////////////////////////////////////////////// \r\nusing UnityEngine;\r\nusing me.caneva20.ConfigAssets.Loading;\r\n\r\nnamespace ");
            
            #line 15 "C:\dev\unity\ConfigAssets\Assets\config-assets\Editor\Builders\EnhancedConfigurationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_namespace));
            
            #line default
            #line hidden
            this.Write(" {\r\n    public partial class ");
            
            #line 16 "C:\dev\unity\ConfigAssets\Assets\config-assets\Editor\Builders\EnhancedConfigurationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_className));
            
            #line default
            #line hidden
            this.Write(" : ScriptableObject {\r\n        private static ");
            
            #line 17 "C:\dev\unity\ConfigAssets\Assets\config-assets\Editor\Builders\EnhancedConfigurationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_className));
            
            #line default
            #line hidden
            this.Write(" _instance;\r\n        ");
            
            #line 18 "C:\dev\unity\ConfigAssets\Assets\config-assets\Editor\Builders\EnhancedConfigurationGenerator.tt"
if(_createSingleton) {
            
            #line default
            #line hidden
            this.Write("public");
            
            #line 18 "C:\dev\unity\ConfigAssets\Assets\config-assets\Editor\Builders\EnhancedConfigurationGenerator.tt"
} else {
            
            #line default
            #line hidden
            this.Write("private");
            
            #line 18 "C:\dev\unity\ConfigAssets\Assets\config-assets\Editor\Builders\EnhancedConfigurationGenerator.tt"
}
            
            #line default
            #line hidden
            this.Write(" static ");
            
            #line 18 "C:\dev\unity\ConfigAssets\Assets\config-assets\Editor\Builders\EnhancedConfigurationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_className));
            
            #line default
            #line hidden
            this.Write(" Instance {\r\n            get {\r\n                if (_instance == null) {\r\n                    _instance = (");
            
            #line 21 "C:\dev\unity\ConfigAssets\Assets\config-assets\Editor\Builders\EnhancedConfigurationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_className));
            
            #line default
            #line hidden
            this.Write(")ConfigLoader.Load(typeof(");
            
            #line 21 "C:\dev\unity\ConfigAssets\Assets\config-assets\Editor\Builders\EnhancedConfigurationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_className));
            
            #line default
            #line hidden
            this.Write("));\r\n                }\r\n\r\n                return _instance;\r\n            }\r\n        }\r\n\r\n");
            
            #line 28 "C:\dev\unity\ConfigAssets\Assets\config-assets\Editor\Builders\EnhancedConfigurationGenerator.tt"
 foreach(var field in _fields) {
            
            #line default
            #line hidden
            this.Write("        public static ");
            
            #line 29 "C:\dev\unity\ConfigAssets\Assets\config-assets\Editor\Builders\EnhancedConfigurationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Type));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 29 "C:\dev\unity\ConfigAssets\Assets\config-assets\Editor\Builders\EnhancedConfigurationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.TargetName));
            
            #line default
            #line hidden
            this.Write(" => Instance.");
            
            #line 29 "C:\dev\unity\ConfigAssets\Assets\config-assets\Editor\Builders\EnhancedConfigurationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 30 "C:\dev\unity\ConfigAssets\Assets\config-assets\Editor\Builders\EnhancedConfigurationGenerator.tt"
}
            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\dev\unity\ConfigAssets\Assets\config-assets\Editor\Builders\EnhancedConfigurationGenerator.tt"

private string __classNameField;

/// <summary>
/// Access the _className parameter of the template.
/// </summary>
private string _className
{
    get
    {
        return this.__classNameField;
    }
}

private string __namespaceField;

/// <summary>
/// Access the _namespace parameter of the template.
/// </summary>
private string _namespace
{
    get
    {
        return this.__namespaceField;
    }
}

private bool __createSingletonField;

/// <summary>
/// Access the _createSingleton parameter of the template.
/// </summary>
private bool _createSingleton
{
    get
    {
        return this.__createSingletonField;
    }
}

private global::me.caneva20.ConfigAssets.Editor.Builders.PropertyDefinition[] __fieldsField;

/// <summary>
/// Access the _fields parameter of the template.
/// </summary>
private global::me.caneva20.ConfigAssets.Editor.Builders.PropertyDefinition[] _fields
{
    get
    {
        return this.__fieldsField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool _classNameValueAcquired = false;
if (this.Session.ContainsKey("_className"))
{
    this.__classNameField = ((string)(this.Session["_className"]));
    _classNameValueAcquired = true;
}
if ((_classNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("_className");
    if ((data != null))
    {
        this.__classNameField = ((string)(data));
    }
}
bool _namespaceValueAcquired = false;
if (this.Session.ContainsKey("_namespace"))
{
    this.__namespaceField = ((string)(this.Session["_namespace"]));
    _namespaceValueAcquired = true;
}
if ((_namespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("_namespace");
    if ((data != null))
    {
        this.__namespaceField = ((string)(data));
    }
}
bool _createSingletonValueAcquired = false;
if (this.Session.ContainsKey("_createSingleton"))
{
    this.__createSingletonField = ((bool)(this.Session["_createSingleton"]));
    _createSingletonValueAcquired = true;
}
if ((_createSingletonValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("_createSingleton");
    if ((data != null))
    {
        this.__createSingletonField = ((bool)(data));
    }
}
bool _fieldsValueAcquired = false;
if (this.Session.ContainsKey("_fields"))
{
    this.__fieldsField = ((global::me.caneva20.ConfigAssets.Editor.Builders.PropertyDefinition[])(this.Session["_fields"]));
    _fieldsValueAcquired = true;
}
if ((_fieldsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("_fields");
    if ((data != null))
    {
        this.__fieldsField = ((global::me.caneva20.ConfigAssets.Editor.Builders.PropertyDefinition[])(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class EnhancedConfigurationGeneratorBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
