name: Create Unity Package

on: 
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
    
    - name: Create Plugins Directory
      run: |
        mkdir -p Plugins
        echo '
        fileFormatVersion: 2
        guid: 3e2c6cc4ecb7a2743bb79b11c213bf82
        folderAsset: yes
        ' > Plugins.meta
        cp -R unity/Assets/config-assets Plugins/
    
    - name: Install Unity Packager
      run: |
          git clone https://github.com/Lachee/Unity-Package-Exporter.git "../tools/unity-package-exporter"
          dotnet publish -c Release -o ../tools "../tools/unity-package-exporter/UnityPackageExporter"
    
    - name: Package Project
      run: |
          echo "Creating package.unitypackage"
          dotnet ../tools/UnityPackageExporter.dll --project Plugins --output package.unitypackage --exclude ".*"
    
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: Unity Package
        path: package.unitypackage
