name: Create Unity Package

on: 
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Create Plugins Directory
      run: |
        mkdir -p Plugins
        echo "fileFormatVersion: 2" > Plugins.meta
        cp -R unity/Assets/config-assets Plugins/
    
    - name: Create meta list
      run: |
        echo "Plugins.meta" > metaList
        find Plugins/ -name \*.meta >> metaList
        cat metaList

    - name: Create package folder
      run: mkdir package

    - name: Create package
      uses: pCYSl5EDgo/create-unitypackage@master
      with:
        path: 'package/config-assets.unitypackage'
        include-files: metaList
    
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        path: package
        name: config-assets
