name: Create Unity Package

on: 
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Unity
      uses: game-ci/unity-setup@v0.1
      with:
        unity-version: 2022.3.1f1
    
    - name: Export Unity package
      run: |
        mkdir export
        /opt/unity/Editor/Unity \
          -projectPath unity \
          -quit -batchmode -nographics -logfile \
          -exportPackage "Assets/config-assets" "export/config-assets.unitypackage"
    
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: Unity Package
        path: export/config-assets.unitypackage
